1

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

[5 4 6 3 2 1]


2

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))

True


3(i)

In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
v, c = np.unique(x, return_counts=True)
m = v[c == c.max()]
i = [np.where(x == k)[0] for k in m]
print(m, i)

[1] [array([0, 5, 7, 8, 9])]


3(ii)

In [5]:
y = np.array([1,1,1,2,3,4,2,4,3,3])
v, c = np.unique(y, return_counts=True)
m = v[c == c.max()]
i = [np.where(y == k)[0] for k in m]
print(m, i)

[1 3] [array([0, 1, 2]), array([4, 8, 9])]


4

In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print(gfg.sum(axis=1))
print(gfg.sum(axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]
